/* Re-downloads the self-hosted font files and regenerates
   src/styles/fonts.css.

   Only needed when the font stack changes — the woff2 files and the
   generated CSS are committed, so a normal build never touches the
   network. Run: npm run fonts

   Fetches with a modern browser UA so Google returns woff2 rather than
   the legacy formats it serves to unknown clients, and keeps only the
   `latin` subset: the store is US-only English, so shipping vietnamese
   and latin-ext would be dead weight on every first paint.

   Archivo is requested WITHOUT its `wdth` axis. Carrying the width axis
   costs 88 KB versus 34 KB for weight alone, and it was driving exactly
   three declarations. 54 KB on every first paint is not worth a width
   difference most visitors would never notice. */

import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const FONT_DIR = join(root, 'public/fonts')

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Archivo:wght@300..800' +
  '&family=Azeret+Mono:wght@300..600' +
  '&display=swap'

const KEEP_SUBSET = 'latin'

mkdirSync(FONT_DIR, { recursive: true })

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

const blocks = [...css.matchAll(/\/\*\s*([\w[\]-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g)]
const wanted = blocks.filter(([, subset]) => subset === KEEP_SUBSET)

if (!wanted.length) {
  console.error('fetch-fonts: no latin subsets found — did the Google CSS format change?')
  process.exit(1)
}

const out = []
for (const [, , block] of wanted) {
  const family = /font-family:\s*'([^']+)'/.exec(block)[1]
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)[1]
  const filename = `${family.replace(/\s+/g, '')}-latin.woff2`

  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer())
  writeFileSync(join(FONT_DIR, filename), bytes)

  let rewritten = block.replace(url, `/fonts/${filename}`)
  if (!rewritten.includes('font-display')) {
    rewritten = rewritten.replace('  src:', '  font-display: swap;\n  src:')
  }
  out.push(`/* ${family} — latin subset, self-hosted */\n${rewritten}`)
  console.log(`  ${filename.padEnd(28)} ${(bytes.length / 1024).toFixed(0)} KB`)
}

writeFileSync(
  join(root, 'src/styles/fonts.css'),
  '/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n' +
    '   Self-hosted so the browser needs no third-party DNS, TLS or\n' +
    '   render-blocking stylesheet before it can paint text. */\n\n' +
    out.join('\n\n') +
    '\n',
  'utf-8'
)
console.log(`fetch-fonts: OK — ${out.length} faces written to src/styles/fonts.css`)
